---
- name: initial_installs
  hosts: BTServers
  remote_user: ubuntu
  become: true
  vars:
   DOCKER_PACKAGES:
   - apt-transport-https
   - ca-certificates
   - curl
   - gnupg-agent
   - software-properties-common
   
  tasks:
   - name: install_git
     yum:
       name: git
       state: present
       update_cache: yes

   - name: install_docker
     apt:
      name: "{{ DOCKER_PACKAGES }}"
      state: present
      force_apt_get: "yes"

   - name: add_docker_gpg_apt_key
     apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

   - name: Save the current Ubuntu release version into a variable
     shell: lsb_release -cs
     register: ubuntu_version

   - name: Add Docker Repository
     apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_version.stdout }} stable"
      state: present

   - name: Update apt packages
     apt:
      update_cache: "yes"
      force_apt_get: "yes"

   - name: Install Docker
     apt:
      name: "docker-ce"
      state: present
      force_apt_get: "yes"

   - name: Test Docker with hello world example
     shell: "docker run hello-world"
     register: hello_world_output

