#!/bin/bash
file=$1
input_start=$2
input_end=$3
run_type=$4
startdate=$(date -I -d "$input_start") || exit -1
enddate=$(date -I -d "$input_end") || exit -1
file='/appcode/input/tmp/symbols/'$1
sd="$startdate"
while [ "$sd" != "$enddate" ]; do
    nd=$(date -I -d "$sd + 1 day")
    current_day=$(date -d "$nd" +%u)
    fromdate=$(date -d "$sd" +%Y-%m-%d)
    todate=$(date -d "$nd" +%Y-%m-%d)
    if [ "$current_day" != 1 ] && [ "$current_day" != 7 ] ; then
    symbols=$(cat $file)
    echo "$symbols" | while read line1; read line2; read line3; read line4;
    do
        docker run -v /appcode/output/positions:/outfile/position backtest:1.0.0  $line1 $fromdate $todate $run_type
        docker run -v /appcode/output/positions:/outfile/position backtest:1.0.0  $line3 $fromdate $todate $run_type
        docker run -v /appcode/output/positions:/outfile/position backtest:1.0.0  $line2 $fromdate $todate $run_type
        docker run -v /appcode/output/positions:/outfile/position backtest:1.0.0  $line4 $fromdate $todate $run_type

    done
    fi
    sd=$(date -I -d "$sd + 4 day")
  # mac option for d decl (the +1d is equivalent to + 1 day)
  # d=$(date -j -v +1d -f "%Y-%m-%d" "2020-12-12" +%Y-%m-%d)
done
