#!/bin/bash
file=$1
fromdate=$2
todate=$3
run_type=$4
    symbols=$(cat $file)
    echo "$symbols" | while read line1; read line2; read line3; read line4;
    do
        docker run -v /appcode/output/positions:/outfile/position backtest:1.0.0  $line1 $fromdate $todate $run_type
        docker run -v /appcode/output/positions:/outfile/position backtest:1.0.0  $line3 $fromdate $todate $run_type
        docker run -v /appcode/output/positions:/outfile/position backtest:1.0.0  $line2 $fromdate $todate $run_type
        docker run -v /appcode/output/positions:/outfile/position backtest:1.0.0  $line4 $fromdate $todate $run_type
    done
    fi
done
